### ISSUE TITLE
Implement Close method?

### ISSUE THREAD

**Issue by jsphweid** [orcaman/writerseeker#4]
I'm using a wav encoding library that seems to only support real files. Since I want to run this wav generation in a the cloud, I need it to work in memory hence how I found this library. The only problem is my writer needs to implement Writer Seeker and Closer. Using this library doesn't satisfy the Closer.

This sort of thing is currently outside my dev domain but is it possible to implement the Close method also?

**Comment by orcaman** [comment]
merged, thanks!
