### ISSUE TITLE
Poor performance when performing many small writes

### ISSUE THREAD

**Issue by derat** [orcaman/writerseeker#6]
You may be aware of this already, but `WriterSeeker` exhibits poor performance when its buffer is grown using many small writes. I encountered this when using it with the [go-audio/wav](https://github.com/go-audio/wav) package's `Encoder` type to write a 1 MB `.wav` file.

Here's a small program demonstrating the performance difference between `WriterSeeker` and `bytes.Buffer` when writing a single byte one million times:

```go
package main

import (
    "bytes"
    "fmt"
    "io"
    "time"

    "github.com/orcaman/writerseeker"
)

func main() {
    const numWrites = 1000000
    doWrites(&writerseeker.WriterSeeker{}, "WriterSeeker", numWrites)
    doWrites(&bytes.Buffer{}, "bytes.Buffer", numWrites)
}

func doWrites(w io.Writer, name string, num int) {
    start := time.Now()
    for i := 0; i < num; i++ {
        if _, err := w.Write([]byte{0}); err != nil {
            panic(fmt.Sprintf("%v failed on write %v: %v", name, i, err))
        }
    }
    fmt.Printf("%v did %v writes in %v\n", name, num, time.Now().Sub(start))
}
```

Here's the output, showing `WriterSeeker` taking about 2000 times as long as `bytes.Buffer`:

```
% go run main.go
WriterSeeker did 1000000 writes in 45.376977075s
bytes.Buffer did 1000000 writes in 21.795908ms
```

It looks like the problem is this code in `Write`, which appears to reallocate the buffer to increase its capacity by just twice the size of the new data being written (i.e. 2 bytes in this case, I think):

```go
	minCap := ws.pos + len(p)
	if minCap > cap(ws.buf) { // Make sure buf has enough capacity:
		buf2 := make([]byte, len(ws.buf), minCap+len(p)) // add some extra
		copy(buf2, ws.buf)
		ws.buf = buf2
	}
	if minCap > len(ws.buf) {
		ws.buf = ws.buf[:minCap]
	}
```

In contrast, I think that `bytes.Buffer`'s `grow` function more-than-doubles its buffer's current capacity: https://golang.org/src/bytes/buffer.go?s=5642:5693#L114

Have you considered using `bytes.Buffer` internally within `WriterSeeker`? I'll send a pull request soon making this change, if you're okay with it. It appears to drop the `WriterSeeker` time of the above example code from 45 seconds to 50 milliseconds.

**Comment by orcaman** [comment]
This is cool! Definitely send a PR :-)
